#!/usr/bin/env php
<?php
require_once "./vendor/autoload.php";
require_once "./src/config/bootstrap.php";
require_once "./src/config/database.php";

use Toolkit\PFlag\Flags;
use Toolkit\PFlag\Flag\Option;
use Toolkit\PFlag\FlagType;
use Toolkit\PFlag\Validator\EnumValidator;

$flags = $_SERVER['argv'];
$scriptFile = array_shift($flags);

$fs = Flags::new();
$fs->setScriptFile($scriptFile);

$fs->setSettings([
  'descNlOnOptLen' => 26
]);

$fs->addOpt('make', 'c', 'Make command to generate scaffolding of various things', FlagType::STRING);

if (!$fs->parse($flags)) {
  // on render help
  return;
}

$make = $fs->getOpt('make');

if (strlen($make) > 0) {
  // TODO: Add for controllers
}

function colorLog($str, $type = 'i')
{
  switch ($type) {
    case 'e': //error
      return "\e[0;31m{$str} \e[0m";
      break;
    case 's': //success
      return "\e[0;32m{$str} \e[0m";
      break;
    case 'w': //warning
      return "\e[0;33m{$str} \e[0m";
      break;
    case 'i': //info
      return "\e[0;36m{$str} \e[0m";
      break;
    default:
      return "";
      break;
  }
}
