#!/usr/bin/env php
<?php
require_once "./vendor/autoload.php";
require_once "./src/config/bootstrap.php";

use Toolkit\PFlag\Exception\FlagParseException;
use Toolkit\PFlag\Flags;
use Toolkit\PFlag\Flag\Option;
use Toolkit\PFlag\FlagType;
use Toolkit\PFlag\Validator\EnumValidator;

$flags = $_SERVER['argv'];
$scriptFile = array_shift($flags);

$fs = Flags::new();
$fs->setScriptFile($scriptFile);

$fs->setSettings([
  'descNlOnOptLen' => 26
]);

$fs->addOpt('make', 'c', 'Make command to generate scaffolding of various things', FlagType::STRING);

try {
    $fs->parse($flags);
} catch (FlagParseException $e) {
    echo colorLog($e->getMessage(), 'e');
    exit(1);
}


$make = $fs->getOpt('make');

if (strlen($make) > 0) {

  if ($make == "controller") {
    $input = readline("Enter controller name: ");

    $directory = "./src/Controllers";

    $newFile = $directory . "/{$input}.php";
    $fileContent = <<<EOL
<?php

namespace Pine\Controllers;

use Pine\App\Controller;
use Pine\App\Request;

class $input extends Controller
{
    public function index(Request \$request) {
        
    }
};
EOL;

    file_put_contents($newFile, $fileContent);

    echo colorLog("Controller file '{$newFile}' created successfully.", 's') . "\n";

    return;
  }
}

function colorLog($str, $type = 'i')
{
  switch ($type) {
    case 'e': //error
      return "\e[0;31m{$str} \e[0m";
      break;
    case 's': //success
      return "\e[0;32m{$str} \e[0m";
      break;
    case 'w': //warning
      return "\e[0;33m{$str} \e[0m";
      break;
    case 'i': //info
      return "\e[0;36m{$str} \e[0m";
      break;
    default:
      return "";
      break;
  }
}
